# Generated by Django 5.0.4 on 2024-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price_expectation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
    ]
